version: "3"

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/src
    ports:
      - "5000:5000"
    command: bash -c "chmod +x ./api.py && ./api.py"
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/src
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
